from __future__ import annotations

MANDATORY_TAG_RULES = [
    {
        "qname": "bus:UKCompaniesHouseRegisteredNumber",
        "label": "UK Companies House registered number",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "company.crn",
    },
    {
        "qname": "bus:BalanceSheetDate",
        "label": "Balance sheet date",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "instant",
        "expected_context": "balance_sheet_date",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "project.balanceSheetDate",
    },
    {
        "qname": "bus:StartDateForPeriodCoveredByReport",
        "label": "Start date for period covered by report",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "instant",
        "expected_context": "reporting_period",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "project.currentPeriodStart",
    },
    {
        "qname": "bus:EndDateForPeriodCoveredByReport",
        "label": "End date for period covered by report",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "instant",
        "expected_context": "reporting_period",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "project.currentPeriodEnd",
    },
    {
        "qname": "bus:EntityCurrentLegalOrRegisteredName",
        "label": "Entity current legal or registered name",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "company.name",
    },
    {
        "qname": "core:DateAuthorisationFinancialStatementsForIssue",
        "label": "Date Authorisation Financial Statements For Issue",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "instant",
        "expected_context": "balance_sheet_date",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "project.authorisationDate",
    },
    {
        "qname": "core:DirectorSigningFinancialStatements",
        "label": "Director Signing Financial Statements",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": True,
        "validation": {"required": True, "non_empty": False, "allowed_values": []},
        "relatedFieldId": "project.directorName",
    },
    {
        "qname": "bus:EntityDormantTruefalse",
        "label": "Entity Dormant True/False",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": True,
        "validation": {"required": True, "non_empty": True, "allowed_values": ["true", "false"]},
        "relatedFieldId": "project.entityDormant",
    },
    {
        "qname": "bus:EntityTradingStatus",
        "label": "Entity Trading Status",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": True,
        "validation": {"required": True, "non_empty": False, "allowed_values": []},
        "relatedFieldId": "project.entityTradingStatus",
    },
    {
        "qname": "bus:AccountingStandardsApplied",
        "label": "Accounting Standards Applied",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": True,
        "validation": {"required": True, "non_empty": False, "allowed_values": []},
        "relatedFieldId": "project.accountingStandardsApplied",
    },
    {
        "qname": "bus:AccountsStatusAuditedOrUnaudited",
        "label": "Accounts Status Audited or Unaudited",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": True,
        "validation": {"required": True, "non_empty": False, "allowed_values": []},
        "relatedFieldId": "project.accountsStatusAuditedOrUnaudited",
    },
    {
        "qname": "bus:AccountsType",
        "label": "Accounts Type",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "entity",
        "expected_unit": None,
        "source": "project_default",
        "usually_hidden": True,
        "validation": {"required": True, "non_empty": False, "allowed_values": []},
        "relatedFieldId": "project.accountsType",
    },
    {
        "qname": "core:AverageNumberEmployeesDuringPeriod",
        "label": "Average number employees during period",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "reporting_period",
        "expected_unit": "pure",
        "source": "template_field",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "notes.averageEmployees.current",
    },
    {
        "qname": "core:ProfitLoss",
        "label": "ProfitLoss",
        "required_for_profiles": ["companies-house-microentity", "companies-house-group-audited"],
        "expected_period": "duration",
        "expected_context": "reporting_period",
        "expected_unit": "default_currency",
        "source": "template_field",
        "usually_hidden": False,
        "validation": {"required": True, "non_empty": True, "allowed_values": []},
        "relatedFieldId": "profitLoss.profitLoss.current",
    },
]


def mandatory_rules_for_profile(profile: str) -> list[dict]:
    return [
        rule for rule in MANDATORY_TAG_RULES if profile in rule["required_for_profiles"]
    ]
